### PR TITLE
measureme: Update memmap to 0.7.0, and bump version to 0.4.1

### PR DESCRIPTION
**Pull request by jackpot51**
memmap 0.7.0 has support for Redox, hence the need for this change. No compatibility issues required fixing, it still passes all tests.

### CODE REVIEW

**Comment by jackpot51** [comment]
There may be other changes since 0.4.0 that necessitate a minor version bump. Please let me know if you want me to bump it to 0.5.0 instead.

**Comment by wesleywiser** [comment]
Thanks for the PR! We've been making other breaking changes since the 0.4 release so the next release will be 0.5. I'd suggest for now, removing the second commit which bumps the measurme version. We'll take care of that when we make the release.

**Comment by wesleywiser** [comment]
Just out of curiosity, any particular reason we're going to `memmap@0.7`? rustc is still on `0.6.2`.

**Comment by michaelwoerister** [comment]
I'll include this change in my version bump to 0.5. Thanks, @jackpot51!

**Pull request closed without merging**
