### PR TITLE
Make summarize useful to data producers other than rustc

### PR DESCRIPTION
**Pull request by wesleywiser**
The [boa project](https://github.com/boa-dev/boa) is using measureme to trace their own performance. This lets them use the `summarize` tool which was previously only useful to rustc because it cared about very specific event kinds.

### CODE REVIEW

**Comment by andjo403** [comment]
nice that you remove the columns that do not have any data makes the printout cleaner

**Comment by andjo403** [comment]
think that this also closes #114

**Comment by wesleywiser** [comment]
Oh, good call. Thanks @andjo403!

**Comment by andjo403** [comment]
hmm #112 also seems to be fixed missed that before

**Pull request merged**
