### PR TITLE
use Inferno to generate flamegraphs

### PR DESCRIPTION
**Pull request by andjo403**
closes https://github.com/rust-lang/measureme/issues/42

### CODE REVIEW

**Comment by bjorn3** [comment]
Keeping the ability to get the raw stack collapsed data is useful. You for example need them to create differential flamegraphs. It is also useful as input for other programs.

**Comment by andjo403** [comment]
shall I add a new crate toolsLib or something like that? and move the measureme/flamegraph/src/stack_collapse.rs there (later maybe also measureme/src/profiling_data.rs can be moved there) and then create the new flamegraph crate.

**Comment by michaelwoerister** [comment]
This looks awesome, thanks @andjo403!

**Comment by wesleywiser** [comment]
@andjo403 Yeah, I think I gave you bad advice on Zulip. Sorry about that! 

I agree with @bjorn3 that `stack_collapse` is useful by itself so we shouldn't remove it.

> create the new flamegraph crate

I think this is the best thing to do. Adding a new crate to the workspace will also let you reuse code from `stack_collapse` inside it since we shouldn't duplicate that logic.

**Comment by andjo403** [comment]
crated the new crates tools_lib and flamegraph

**Pull request merged**
