### PR TITLE
chore: share license information across the entire workspace

### PR DESCRIPTION
**Pull request by weihanglo**
This was found during the course of vendoring rustc-perf in rust-lang/rust repo: <https://github.com/rust-lang/rust/pull/125465#issuecomment-2130745904>.
Some packages don't have a license field defined and failed license-check in tidy.

The symlinks are also essential. When `cargo package` create a `.crate` tarball, those licenses should be included in each package.

If sharing workspace information is something we want, I could include more in follow-ups.

### CODE REVIEW

**Comment by weihanglo** [comment]
Friendly @michaelwoerister, since you're the person committing to this repository most recent :)

**Review by michaelwoerister — APPROVED** [review]

**Comment by michaelwoerister** [comment]
Thanks, @weihanglo! Do we need a release for this to fix the rust-lang/rust issue?

**Comment by weihanglo** [comment]
Yeah thanks @michaelwoerister! I would love to see new releases for fixing the <https://github.com/rust-lang/rust/pull/125465>, though it might also require some old version to get released, as well as publish some new packages.

I am still working on improving the infrastructure to make it easier to release new versions (e.g. #228). I'll let you know what are needed to publish once I figure them out.

**Comment by michaelwoerister** [comment]
Yeah, we might need to backport some of these changes to 10.1.x and 9.2.x if anything other than measureme itself is referenced from the Rust repo.

**Pull request merged**
