### PR TITLE
summarize: Make incr-cache-loading and query-blocking contribute to self-time of query.

### PR DESCRIPTION
**Pull request by michaelwoerister**
Adjusts the logic in `summarize` according to https://github.com/rust-lang/measureme/issues/75#issuecomment-563137947. 

The differences in absolute numbers should be small. But it is more consistent, I think.

Fixes https://github.com/rust-lang/measureme/issues/75.

r? @wesleywiser

### CODE REVIEW

**Comment by michaelwoerister** [comment]
I might make sense to do a new release for this and switch perf.rlo over. It is the last thing missing for the MVP, I'd say.

**Comment by andjo403** [comment]
to me this looks good.
but maybe before a new release, something that you talked about in the issue was total time and maybe you are thinking the total time for a label the same as in chrome tracing where you have a self time and total time for an event and I think that is missing from showing all information for an events. I also think that the total time is needed for e.g. in https://github.com/rust-lang/measureme/issues/67

**Comment by michaelwoerister** [comment]
@andjo403, I think what you are talking about I have seen being referred to as "inclusive" and "exclusive" times for an event. "Inclusive" would then also contain the time of child events. I think calling it "inclusive" and "exclusive" times is pretty good. Right now we only show "exclusive" times (what we call "self time"), adding a column for inclusive time to perf.rlo is a very good idea.

**Comment by michaelwoerister** [comment]
Hm, kCacheGrind and https://github.com/KDAB/hotspot call it "self" and "inclusive" times.

**Comment by wesleywiser** [comment]
The Chrome profile calls this "self time" vs "total time" FWIW

**Pull request merged**
