### PR TITLE
Bump version after MmapSerializationSink bug fix.

### PR DESCRIPTION
**Pull request by michaelwoerister**
Next try...
r? @wesleywiser

### CODE REVIEW

**Comment by michaelwoerister** [comment]
I'll have to read up on `git tag` :)

**Comment by michaelwoerister** [comment]
OK, I ran `git tag -a 0.2.1 -m "0.2.1 release"` and pushed but I'm not sure that did anything.

**Comment by wesleywiser** [comment]
Did you do `git push --tags`?

**Comment by michaelwoerister** [comment]
I did this now: `git push origin 0.2.1`. That seemed to have worked.

**Comment by wesleywiser** [comment]
Hmm... it doesn't look like it's shown up in GitHub yet. What's `git remote -v` say?

**Comment by michaelwoerister** [comment]
```
origin	git@github.com:michaelwoerister/measureme.git (fetch)
origin	git@github.com:michaelwoerister/measureme.git (push)
upstream	https://github.com/rust-lang/measureme.git (fetch)
upstream	https://github.com/rust-lang/measureme.git (push)
```

**Comment by michaelwoerister** [comment]
Do I need to push directly to `upstream`? That seems sub-optimal.

**Comment by wesleywiser** [comment]
Oh ok. You need to push it directly to `upstream`

**Comment by wesleywiser** [comment]
Yeah, tags don't really participate in merges like commits do. They pretty much just live in the global "namespace" within a repo.

**Comment by michaelwoerister** [comment]
Is there a way to add tags via github?

**Comment by wesleywiser** [comment]
Hmm it looks like you can do it from the Releases page https://help.github.com/en/articles/creating-releases

**Comment by michaelwoerister** [comment]
OK, it worked. It need to find a good workflow for this... Thanks for your patience `:)`

**Comment by wesleywiser** [comment]
Of course! I hope there's some cargo plugin that does all this for us

**Pull request merged**
